version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
  mysqldb:
    image: "mysql:5.7"
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "bachelor"
      MYSQL_USER: "karamitosnikos"
      MYSQL_PASSWORD: "karamitosnikos"
      MYSQL_ROOT_PASSWORD: "karamitosnikos"

volumes:
  mysql-data:

