version: "3.9"
services:
  server:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysqldb:3306/bachelor"
      SPRING_DATASOURCE_USERNAME: "karamitosnikos"
      SPRING_DATASOURCE_PASSWORD: "karamitosnikos"
    depends_on:
      mysqldb: 
        condition: service_healthy

  mysqldb:
    image: "mysql:5.7"
    restart: always
    ports:
      - "3307:3306"
    command:
       --character-set-server=utf8mb4 
       --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "bachelor"
      MYSQL_USER: "karamitosnikos"
      MYSQL_PASSWORD: "karamitosnikos"
      MYSQL_ROOT_PASSWORD: "karamitosnikos"
    healthcheck:
      test: out=$$(mysqladmin ping -h localhost -P 3306 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD 2>&1); echo $$out | grep 'mysqld is alive' || { echo $$out; exit 1; }
      interval: 20s
      retries: 5

volumes:
  mysql-data:
